[project]
name = "centreon-mcp"
version = "0.0.1"
description = "Centreon MCP Server"
authors = [
  {name = "Grégory Leventoux", email = "gleventoux@centreon.com"}
]
maintainers = [
  {name = "Grégory Leventoux", email = "gleventoux@centreon.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=3.2.4",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "coverage>=7.13.5",
    "mypy>=1.20.1",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.10",
]

[project.scripts]
centreon-mcp-server = "centreon_mcp.__main__:main"

[tool.uv]
package = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
